```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(corrplot)
library(ggplot2)
library(patchwork)
library(mgcv)
library(qgam)
library(quantreg)
library(car)
library(splines)
library(WRTDStidal)
library(scales)
```

```{r}
data <- read.csv("../datasets/miami-housing.csv")
str(data)
```

```{r}
data <- data %>%
  mutate(
    structure_quality = as.factor(structure_quality),
    month_sold = as.factor(month_sold),
    avno60plus = as.factor(avno60plus)
  )
```

```{r}
sum(is.na(data))
```

```{r}
set.seed(1)

data_split <- initial_split(data, prop = 0.8, strata = structure_quality)

train_data <- training(data_split)
train_data <- train_data %>% slice_sample(prop = 1)
test_data  <- testing(data_split)
test_data <- test_data %>% slice_sample(prop = 1)
```

# Pradinė analizė

```{r}
str(data)
```

## Išskirtys

```{r}
count_outliers <- function(data, var_name) {
  data %>%
    summarise(
      variable = var_name,
      Q1 = quantile(.data[[var_name]], 0.25),
      Q3 = quantile(.data[[var_name]], 0.75),
      H = Q3 - Q1,
      inner_low = Q1 - 1.5*H,
      inner_high = Q3 + 1.5*H,
      outer_low = Q1 - 3*H,
      outer_high = Q3 + 3*H,
      mild_outliers = sum((.data[[var_name]] < inner_low & .data[[var_name]] > outer_low) | (.data[[var_name]] > inner_high &   .data[[var_name]] < outer_high)),
      extreme_outliers = sum(.data[[var_name]] < outer_low | .data[[var_name]] > outer_high)
      )
}

numeric_cols <- data %>% 
  dplyr::select(where(is.numeric)) %>% 
  dplyr::select(-LATITUDE, -LONGITUDE, -PARCELNO) %>% 
  names()

results_list <- lapply(numeric_cols, function(col) count_outliers(data, col))
outlier_summary <- bind_rows(results_list)
outlier_summary
```

```{r fig.height=2.5, fig.width=5.4, message=FALSE, warning=FALSE}
p1 <- data %>% ggplot(aes(y=SALE_PRC, x=as.factor(avno60plus))) +
  geom_boxplot(size = 0.5) + 
  theme_bw() +
  scale_y_continuous(labels = label_number(scale = 1e-6)) +
  labs(x = 'Triukšmas', y = 'Kaina (mln.)')

p2 <- data %>% ggplot(aes(y=SALE_PRC, x=as.factor(month_sold))) +
  geom_boxplot(size = 0.5) + 
  theme_bw() +
  labs(x = 'Mėnesis', y = NULL) +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank())

p3 <- data %>% ggplot(aes(y=SALE_PRC, x=as.factor(structure_quality))) +
  geom_boxplot(size = 0.5) + 
  theme_bw() +
  labs(x = 'Kokybė', y = NULL) +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank())

p1 + p2 + p3

ggsave(filename = "boxplot_3x.png", width = 5.4, height = 2.5, units = "in", dpi = 300)
```

```{r}
data_long <- data %>%
  dplyr::select(-LATITUDE, -LONGITUDE, -PARCELNO, -avno60plus, -month_sold, -structure_quality) %>%
  pivot_longer(
    cols = everything(), 
    names_to = "variable", 
    values_to = "value"
  )

data_long$variable <- as.factor(data_long$variable)

head(data_long)
```

```{r fig.height=4, fig.width=12}
data_long %>% 
  ggplot(aes(x = variable, y = value, fill = variable)) +
  geom_boxplot(outlier.alpha = 0.2) +
  facet_wrap(~variable, scales = "free", ncol = 6) + 
  theme_bw()
```

## Charakteristikos

```{r}
char <- data %>% 
  summarise(across(where(is.numeric),
            list(min = ~min(.x, na.rm = TRUE), 
                 max = ~max(.x, na.rm = TRUE),
                 mean = ~mean(.x, na.rm = TRUE), 
                 sd = ~sd(.x, na.rm = TRUE),
                 q25 = ~quantile(.x, 0.25, na.rm = TRUE),
                 median = ~median(.x, na.rm = TRUE),
                 q75 = ~quantile(.x, 0.75, na.rm = TRUE)))) %>% 
  pivot_longer(cols = everything(), 
               names_to = c("Variable", ".value"),
               names_pattern = "(.*)_(min|max|mean|sd|median|q25|q75)") %>% 
  mutate(across(where(is.numeric), ~ round(.x, 4)))
char
```

## Kokybinių kintamųjų analizė

```{r}
table(data$avno60plus)
```

```{r}
table(data$structure_quality)
```

```{r}
table(data$structure_quality, data$avno60plus)
```

## Sąryšiai

```{r}
ggplot(data, aes(x = SALE_PRC)) +
  geom_histogram(color = "white", fill = "royalblue", bins = 50) + 
  geom_vline(aes(xintercept = quantile(SALE_PRC, 0.9)),
             color = "red", linetype = "dashed", linewidth = 1) +
  annotate("text", x = quantile(data$SALE_PRC, 0.9) + 400000, y = 2000, 
           label = "90 % kvantilis", vjust = 2, color = "red", size = 4) +
  scale_x_continuous(
    labels = label_number(scale = 1e-6, decimal.mark = ","),
    breaks = seq(0, max(data$SALE_PRC, na.rm = TRUE), by = 500000)) +
  theme_bw() +
  labs(subtitle = "Raudona brūkšninė linija žymi 90 % visų stebėjimų kainos ribą",
       x = "Kaina (mln., USD)",
       y = "Dažnis")

#ggsave(filename = "atsakas-histograma.png", width = 5.4, height = 3, units = "in", dpi = 300)
```

```{r}
numeric_values <- data %>% 
  dplyr::select(where(is.numeric)) %>% 
  dplyr::select(-LATITUDE, -LONGITUDE, -PARCELNO) %>%
  rename(
    "Pardavimo kaina" = SALE_PRC,
    "Žemės plotas" = LND_SQFOOT,
    "Bendras plotas" = TOT_LVG_AREA,
    "Papildomų objektų vertė" = SPEC_FEAT_VAL,
    "Atstumas (stotis)" = RAIL_DIST,
    "Atstumas (jūra)" = OCEAN_DIST,
    "Atstumas (vandens telkinys)" = WATER_DIST,
    "Atstumas (verslo rajono)" = CNTR_DIST,
    "Atstumas (rajono centras)" = SUBCNTR_DI,
    "Atstumas (greitkelis)" = HWY_DIST,
    "Statinio amžius" = age
  )

cor_matrix <- cor(numeric_values, method = "spearman", use = "complete.obs")

#png(filename = "corr_heatmap.png", width = 57, height = 4.5, units = "in", res = 300)

options(OutDec = ",")
corrplot(cor_matrix, 
         method = "color", 
         addCoef.col = "black", 
         tl.col = "black",
         tl.cex = 0.75,
         number.cex = 0.55,
         type = 'lower',
         diag = FALSE)
options(OutDec = ".")

#dev.off()
```

```{r}
numeric_values
```

```{r message=FALSE, warning=FALSE}
numeric_values %>%
  pivot_longer(cols = -`Pardavimo kaina`, 
               names_to = "kintamasis", 
               values_to = "reiksme") %>%
  ggplot(aes(x = reiksme, y = `Pardavimo kaina`)) +
  geom_point(alpha = 0.4, size = 0.95, color = "royalblue") +
  geom_quantile(quantiles = 0.5, color = "orange", linewidth = 0.75) + 
  geom_quantile(quantiles = 0.1, color = "cyan2", linewidth = 0.6) + 
  geom_quantile(quantiles = 0.9, color = "green", linewidth = 0.6) + 
  facet_wrap(~kintamasis, scales = "free_x", ncol = 5) +
  scale_y_continuous(labels = label_number(scale = 1e-6)) +
  coord_cartesian(ylim = c(0, 3000000)) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "grey95"),
    strip.text = element_text(size = 7),
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(subtitle = "Oranžinė - mediana, žydra - 10 %, žalia - 90 % kvantilis",
       x = "Reikšmė",
       y = "Kaina (mln., USD)")

#ggsave(filename = "sklaida.png", width = 6.7, height = 4, units = "in", dpi = 300)
```

```{r}
p0 <- ggplot(data, aes(x = HWY_DIST, y = SALE_PRC)) +
  geom_point(alpha = 0.3) +
  geom_quantile(quantiles = 0.5, color = "orange", linewidth = 0.75) + 
  geom_quantile(quantiles = c(0.1, 0.90), color = "cyan2", linewidth = 0.6) + 
  labs(title = "Originalus") +
  theme_bw()

p1 <- ggplot(data, aes(x = log(HWY_DIST), y = SALE_PRC)) +
  geom_point(alpha = 0.3) +
  geom_quantile(quantiles = 0.5, color = "orange", linewidth = 0.75) + 
  geom_quantile(quantiles = c(0.1, 0.90), color = "cyan2", linewidth = 0.6) + 
  labs(title = "log") +
  theme_bw()

p2 <- ggplot(data, aes(x = sqrt(HWY_DIST), y = SALE_PRC)) +
  geom_point(alpha = 0.3) +
  geom_quantile(quantiles = 0.5, color = "orange", linewidth = 0.75) + 
  geom_quantile(quantiles = c(0.1, 0.90), color = "cyan2", linewidth = 0.6) + 
  labs(title = "sqrt") +
  theme_minimal()

p3 <- ggplot(data, aes(x = 1/(HWY_DIST + 0.001), y = SALE_PRC)) +
  geom_point(alpha = 0.3) +
  geom_quantile(quantiles = 0.5, color = "orange", linewidth = 0.75) + 
  geom_quantile(quantiles = c(0.1, 0.90), color = "cyan2", linewidth = 0.6) + 
  labs(title = "1/x+1") +
  theme_light()

(p0 + p1) / (p2 + p3)
```

```{r}
cor(log(test_data$CNTR_DIST), log(test_data$SUBCNTR_DI), use = "complete.obs")
```

# Modelis

```{r}
linear_model <- lm(SALE_PRC ~  log(LND_SQFOOT)+TOT_LVG_AREA+log(SPEC_FEAT_VAL+1)+log(OCEAN_DIST)+log(CNTR_DIST)+log(SUBCNTR_DI)+log(HWY_DIST) + structure_quality, data=train_data)
vif(linear_model)
```

```{r}
pinball_loss <- function(y_true, y_pred, tau) {
  error <- y_true - y_pred
  loss <- ifelse(error >= 0, tau * error, (tau - 1) * error)
  return(mean(loss))
}
```

## Verslo centro modelis

```{r}
cntr_model <- rq(SALE_PRC ~ 
                   log(LND_SQFOOT) + TOT_LVG_AREA + 
                   log(SPEC_FEAT_VAL+1) + log(OCEAN_DIST) +
                   log(CNTR_DIST) + log(HWY_DIST) + structure_quality, 
                 data=train_data, tau = 0.9)

summary(cntr_model)
```

```{r}
pred <- predict(cntr_model, newdata = test_data)
actual <- test_data$SALE_PRC

mae <- mean(abs(actual - pred))
rmse <- sqrt(mean((actual - pred)^2))
rho <- cor(pred, actual, method='spearman')

pataikyta <- mean(actual <= pred)

res <- resid(cntr_model)
mod_nl <- rq((SALE_PRC) ~ 1, tau = 0.90, data = train_data)
rsd_nl <- resid(mod_nl)

pseudo_r2 <- goodfit(res, rsd_nl, 0.90)

loss_value <- pinball_loss(actual, pred, 0.9)

cat("MAE:", mae, "\nRMSE:", rmse, "\nSpearman:", rho, "\nPataikymo dažnis:", pataikyta, "\nPseudo R2 (tau = 0.9):", pseudo_r2, "\n Vidutinė kvantilių paklaida: ", loss_value)
```

```{r}
ggplot(test_data, aes(x = SALE_PRC, y = pred)) +
  geom_point(alpha = 0.3, color = "darkblue") +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(title = "Tikros ir prognozuotos kainos",
       x = "Tikra kaina",
       y = "Prognozuota kaina (0,9 kvantilis)") +
  theme_minimal()
```



## Rajono centro modelis

```{r}
subcntr_model <- rq(SALE_PRC ~ log(LND_SQFOOT)+TOT_LVG_AREA+log(SPEC_FEAT_VAL+1)+log(OCEAN_DIST)+
                            log(SUBCNTR_DI)+log(HWY_DIST)+structure_quality, 
                 data=train_data, tau = 0.9)

summary(subcntr_model)
```

```{r}
pred <- predict(subcntr_model, newdata = test_data)
actual <- test_data$SALE_PRC

mae <- mean(abs(actual - pred))
rmse <- sqrt(mean((actual - pred)^2))
rho <- cor(pred, actual, method='spearman')

pataikyta <- mean(actual <= pred)

res <- resid(subcntr_model)
mod_nl <- rq((SALE_PRC) ~ 1, tau = 0.90, data = train_data)
rsd_nl <- resid(mod_nl)

aic <- AIC(subcntr_model)


pseudo_r2 <- goodfit(res, rsd_nl, 0.90)

loss_value <- pinball_loss(actual, pred, 0.9)

cat("MAE:", mae, "\nRMSE:", rmse, "\nSpearman:", rho, "\nPataikymo dažnis:", pataikyta, "\nPseudo R2 (tau = 0.9):", pseudo_r2, "\nAIC:", aic, "\n Vidutinė kvantilių paklaida: ", loss_value)
```

```{r}
ggplot(test_data, aes(x = SALE_PRC, y = pred)) +
  geom_point(alpha = 0.3, color = "darkblue") +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(title = "Tikros ir prognozuotos kainos",
       x = "Tikra kaina",
       y = "Prognozuota kaina (0,9 kvantilis)") +
  theme_minimal()
```

## Bendras modelis

```{r}
model <- rq(SALE_PRC ~ 
                   log(LND_SQFOOT) + TOT_LVG_AREA + 
                   log(SPEC_FEAT_VAL+1) + log(OCEAN_DIST) +log(SUBCNTR_DI)+ 
                   log(CNTR_DIST) + log(HWY_DIST) + structure_quality, 
                 data=train_data, tau = 0.9)

summary(model)

```

```{r}
pred <- predict(model, newdata = test_data)
actual <- test_data$SALE_PRC

mae <- mean(abs(actual - pred))
rmse <- sqrt(mean((actual - pred)^2))
rho <- cor(pred, actual, method='spearman')

pataikyta <- mean(actual <= pred)

res <- resid(model)
mod_nl <- rq((SALE_PRC) ~ 1, tau = 0.90, data = train_data)
rsd_nl <- resid(mod_nl)

aic <- AIC(model)

pseudo_r2 <- goodfit(res, rsd_nl, 0.90)

loss_value <- pinball_loss(actual, pred, 0.9)

cat("MAE:", mae, "\nRMSE:", rmse, "\nSpearman:", rho, "\nPataikymo dažnis:", pataikyta, "\nPseudo R2 (tau = 0.9):", pseudo_r2, "\nAIC:", aic, "\nVidutinė kvantilių paklaida: ", loss_value)
```

# Sąveikos


```{r}
final_model <- rq(SALE_PRC ~ 
                   log(LND_SQFOOT) + TOT_LVG_AREA + 
                   log(SPEC_FEAT_VAL+1) + log(OCEAN_DIST) + log(SUBCNTR_DI)+ 
                   log(CNTR_DIST) + log(HWY_DIST) + structure_quality + log(CNTR_DIST):TOT_LVG_AREA, 
                 data=train_data, tau = 0.9)

summary(final_model)

```

```{r}
rezultatai <- summary(final_model, se = "boot")$coefficients

lower <- rezultatai[,1] - 1.96 * rezultatai[,2]
upper <- rezultatai[,1] + 1.96 * rezultatai[,2]

tavo_lentele <- cbind(rezultatai[,1], lower, upper)
colnames(tavo_lentele) <- c("Beta", "Lower_95", "Upper_95")
print(tavo_lentele)
```


```{r}
pred <- predict(final_model, newdata = test_data)
actual <- test_data$SALE_PRC

mae <- mean(abs(actual - pred))
rmse <- sqrt(mean((actual - pred)^2))
rho <- cor(pred, actual, method='spearman')

pataikyta <- mean(actual <= pred)

res <- resid(final_model)
mod_nl <- rq((SALE_PRC) ~ 1, tau = 0.90, data = train_data)
rsd_nl <- resid(mod_nl)

aic <- AIC(final_model)

pseudo_r2 <- goodfit(res, rsd_nl, 0.90)

loss_value <- pinball_loss(actual, pred, 0.9)

cat("MAE:", mae, "\nRMSE:", rmse, "\nSpearman:", rho, "\nPataikymo dažnis:", pataikyta, "\nPseudo R2 (tau = 0.9):", pseudo_r2, "\nAIC:", aic, "\nVidutinė kvantilių paklaida: ", loss_value)
```


```{r}
ggplot(test_data, aes(x = SALE_PRC, y = pred)) +
  geom_point(alpha = 0.45, color = "darkblue") +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  scale_x_continuous(
    labels = label_number(scale = 1e-6, decimal.mark = ",")) +
  scale_y_continuous(
    labels = label_number(scale = 1e-6, decimal.mark = ",")) +
  coord_cartesian(xlim = c(0, 4000000), ylim = c(0, 4000000)) +
  labs(title = "Tikros ir prognozuotos kainos (0,9 kvantilis)",
       x = "Tikra kaina (mln., USD)",
       y = "Prognozuota kaina (mln., USD)") +
  theme_bw()

ggsave(filename = "real_vs_fitted.png", width = 5, height = 3, units = "in", dpi = 300)
```


```{r fig.width=10}
qs <- 1:9/10
qr2 <- rq(SALE_PRC ~ log(LND_SQFOOT) + TOT_LVG_AREA + log(SPEC_FEAT_VAL+1) + log(OCEAN_DIST) + log(SUBCNTR_DI) + 
                     log(CNTR_DIST) + log(HWY_DIST) + structure_quality + log(CNTR_DIST):TOT_LVG_AREA,
          data=train_data, tau = qs)

plot(summary(qr2))
summary(qr2)
```

```{r}
lt_titles <- c(
  "(Intercept)" = "Intercept",
  "log(LND_SQFOOT)" = "log(Žemės plotas)",
  "TOT_LVG_AREA" = "Bendras plotas",
  "log(SPEC_FEAT_VAL + 1)" = "log(Papildomų objektų vertė)",
  "log(OCEAN_DIST)" = "log(Atstumas iki jūros)",
  "log(SUBCNTR_DI)" = "log(Atstumas iki rajono centro)",
  "log(CNTR_DIST)" = "log(Atstumas iki verslo rajono)",
  "log(HWY_DIST)" = "log(Atstumas iki greitkelio)",
  "structure_quality2" = "Statinio kokybė: 2",
  "structure_quality3" = "Statinio kokybė: 3",
  "structure_quality4" = "Statinio kokybė: 4",
  "structure_quality5" = "Statinio kokybė: 5",
  "TOT_LVG_AREA:log(CNTR_DIST)" = "Bendras plotas : Atstumas iki centro (sąveika)"
)

par(mfrow = c(1, 1))

for (i in 1:length(lt_titles)) {
  en_name <- names(lt_titles)[i]
  lt_name <- lt_titles[i]
  
  plot(summary(qr2), 
       parm = en_name, 
       main = lt_name,
       xlab = "Kvantilis", 
       ylab = "Koeficientas")
}
```


# Kovariančių svarba

```{r}
train_data_std <- train_data

train_data_std$LND_SQFOOT_std   <- scale(log(train_data$LND_SQFOOT))
train_data_std$TOT_LVG_AREA_std <- scale(train_data$TOT_LVG_AREA)
train_data_std$SPEC_FEAT_std    <- scale(log(train_data$SPEC_FEAT_VAL + 1))
train_data_std$OCEAN_DIST_std   <- scale(log(train_data$OCEAN_DIST))
train_data_std$SUBCNTR_DI_std   <- scale(log(train_data$SUBCNTR_DI))
train_data_std$CNTR_DIST_std    <- scale(log(train_data$CNTR_DIST))
train_data_std$HWY_DIST_std     <- scale(log(train_data$HWY_DIST))

final_model_std <- rq(log(SALE_PRC) ~ 
                        LND_SQFOOT_std + 
                        TOT_LVG_AREA_std + 
                        SPEC_FEAT_std + 
                        OCEAN_DIST_std + 
                        SUBCNTR_DI_std + 
                        CNTR_DIST_std + 
                        HWY_DIST_std + 
                        structure_quality + 
                        CNTR_DIST_std:TOT_LVG_AREA_std, 
                      data = train_data_std, tau = 0.9)

summary(final_model_std, se = "boot")

sort(abs(coef(final_model_std)), decreasing = TRUE)
```


### Kryžminė patikra

```{r}
set.seed(123)
k <- 10
data <- data[sample(nrow(data)), ]
folds <- cut(seq(1, nrow(data)), breaks = k, labels = FALSE)

cv_scores_loss <- numeric(k)
cv_scores_goodfit <- numeric(k)

for(i in 1:k) {
  test_indices <- which(folds == i, arr.ind = TRUE)
  train_data_cv <- data[-test_indices, ]
  test_data_cv <- data[test_indices, ]
  
  fit <- rq(SALE_PRC ~ 
                   log(LND_SQFOOT) + TOT_LVG_AREA + 
                   log(SPEC_FEAT_VAL+1) + log(OCEAN_DIST) + log(SUBCNTR_DI)+ 
                   log(CNTR_DIST) + log(HWY_DIST) + structure_quality + log(CNTR_DIST):TOT_LVG_AREA, 
            tau = 0.9, data = train_data_cv)
  
  preds <- predict(fit, newdata = test_data_cv)
  
  res <- resid(fit)
  mod_nl <- rq((SALE_PRC) ~ 1, tau = 0.90, data = train_data)
  rsd_nl <- resid(mod_nl)
  
  cv_scores_loss[i] <- pinball_loss(test_data_cv$SALE_PRC, preds, 0.9)
  cv_scores_goodfit[i] <- goodfit(res, rsd_nl, 0.90)
}

mean(cv_scores_loss)
mean(cv_scores_goodfit)
```



















------------------------------------------------------------------------

# SENI BANDYMAI

```{r}
#gg_loess_age <- ggplot(data, aes(x = age, y = SALE_PRC)) +
#  geom_point() +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "blue")

#gg_loess_lvg_area <- ggplot(data, aes(x = TOT_LVG_AREA, y = SALE_PRC)) +
#  geom_point() +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "blue")

#gg_loess_spec_val <- ggplot(data, aes(x = SPEC_FEAT_VAL, y = SALE_PRC)) +
#  geom_point() +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "blue")

#gg_loess_lnd_sqfoot <- ggplot(data, aes(x = LND_SQFOOT, y = SALE_PRC)) +
#  geom_point() +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "blue")

#(gg_loess_lvg_area + gg_loess_age) / (gg_loess_spec_val + gg_loess_lnd_sqfoot)
```

DIST 4 požymiai

```{r}
#gg_loess_rail_dist <- ggplot(data, aes(x = RAIL_DIST, y = log(SALE_PRC))) +
#  geom_point(size = .8, alpha = .5) +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "red")

#gg_loess_ocean_dist <- ggplot(data, aes(x = OCEAN_DIST, y = log(SALE_PRC))) +
#  geom_point(size = .8, alpha = .5) +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "red")

#gg_loess_spec_cntr_dist <- ggplot(data, aes(x = CNTR_DIST, y = log(SALE_PRC))) +
#  geom_point(size = .8, alpha = .5) +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "red")

#gg_loess_hwy_dist <- ggplot(data, aes(x = HWY_DIST, y = log(SALE_PRC))) +
#  geom_point(size = .8, alpha = .5) +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "red")

#(gg_loess_rail_dist + gg_loess_ocean_dist) / (gg_loess_spec_cntr_dist + gg_loess_hwy_dist)
```

Pilnas

```{r}
#gam_model <- gam(SALE_PRC ~ s(RAIL_DIST, k=18) + s(OCEAN_DIST, k=20) + s(CNTR_DIST, k=15) + s(HWY_DIST, k=15), 
#                 data = data, 
#                 method = "REML")
```

```{r}
#plot(gam_model, pages = 1, shade = TRUE, residuals = TRUE)
#summary(gam_model)
```

```{r}
#gam.check(gam_model)
```

```{r}
#plot(gam_model, select = 1, residuals = TRUE, 
#     col = "gray70", pch = 16, cex = 0.4)

#p <- predict(gam_model, type = "terms", se.fit = TRUE)
#x_val <- data$RAIL_DIST
#y_val <- p$fit[, "s(RAIL_DIST)"]

#ord <- order(x_val)
#lines(x_val[ord], y_val[ord], col = "red", lwd = 2)
#===============================================================================
#plot(gam_model, select = 2, residuals = TRUE, 
#     col = "gray70", pch = 16, cex = 0.4)

#p <- predict(gam_model, type = "terms", se.fit = TRUE)
#x_val <- data$OCEAN_DIST
#y_val <- p$fit[, "s(OCEAN_DIST)"]

#ord <- order(x_val)
#lines(x_val[ord], y_val[ord], col = "red", lwd = 2)
#===============================================================================
#plot(gam_model, select = 3, residuals = TRUE, 
#     col = "gray70", pch = 16, cex = 0.4)

#p <- predict(gam_model, type = "terms", se.fit = TRUE)
#x_val <- data$CNTR_DIST
#y_val <- p$fit[, "s(CNTR_DIST)"]

#ord <- order(x_val)
#lines(x_val[ord], y_val[ord], col = "red", lwd = 2)
#===============================================================================
#plot(gam_model, select = 4, residuals = TRUE, 
#     col = "gray70", pch = 16, cex = 0.4)

#p <- predict(gam_model, type = "terms", se.fit = TRUE)
#x_val <- data$HWY_DIST
#y_val <- p$fit[, "s(HWY_DIST)"]

#ord <- order(x_val)
#lines(x_val[ord], y_val[ord], col = "red", lwd = 2)
```

```{r}
#fit_ols <- lm(SALE_PRC ~ RAIL_DIST, data = data)
#fit_q <- rq(SALE_PRC ~ RAIL_DIST, tau = c(0.1, 0.5, 0.9), data = data)
```

```{r eval=FALSE, warning=FALSE, include=FALSE}
#fit_all <- rq(SALE_PRC ~ OCEAN_DIST + RAIL_DIST + CNTR_DIST + HWY_DIST + LND_SQFOOT + TOT_LVG_AREA + SPEC_FEAT_VAL + WATER_DIST + SUBCNTR_DI + age, tau = seq(0.05, 0.95, by = 0.05), data = data)
#plot(summary(fit_all))
```

```{r}
#lm_mdl <- lm(SALE_PRC ~ OCEAN_DIST + RAIL_DIST + CNTR_DIST + HWY_DIST + LND_SQFOOT + TOT_LVG_AREA + SPEC_FEAT_VAL + WATER_DIST + SUBCNTR_DI + age + WATER_DIST + as.factor(structure_quality) + as.factor(avno60plus), data = data)
#vif(lm_mdl)
```

```{r}
#qgam_mdl <- qgam(SALE_PRC ~ OCEAN_DIST + RAIL_DIST + CNTR_DIST + HWY_DIST + LND_SQFOOT + TOT_LVG_AREA + SPEC_FEAT_VAL + WATER_DIST + SUBCNTR_DI + age, 
#                   qu = 0.90, 
#                   data = data)
```

------------------------------------------------------------------------

```{r}
#rq_mdl <- rq(log(SALE_PRC) ~ ns(OCEAN_DIST, df =3) + ns(CNTR_DIST, df =4) + HWY_DIST + LND_SQFOOT + TOT_LVG_AREA + SPEC_FEAT_VAL + age + as.factor(structure_quality), tau = 0.9, data = train_data)
```

```{r}
#summary(qgam_mdl)
#summary(rq_mdl)
```

```{r}
#fit_ns <- rq(log(SALE_PRC) ~ ns(age, df =4), data = data, tau = 0.9)
# Generate a sequence of weights for prediction
#plot_data <- data.frame(age = seq(min(data$age), max(data$age), length.out = 100))

# Predict values
#plot_data$pred <- exp(predict(fit_ns, newdata = plot_data))

# Plotting
#plot(data$age, data$SALE_PRC, pch = 19, col = "gray", main = "Quantile Spline Regression")
#lines(plot_data$age, plot_data$pred, col = "blue", lwd = 2)
```

```{r}
#pred <- predict(rq_mdl, newdata = test_data)
#actual <- log(test_data$SALE_PRC)

#mae <- mean(abs(actual - pred))
#mae

#rmse <- sqrt(mean((actual - pred)^2))
#rmse

#cor(pred, actual)

#mean(actual <= pred)


#res <- resid(rq_mdl)
#mod_nl <- rq(log(SALE_PRC) ~ 1, tau = 0.9, data = train_data)
#rsd_nl <- resid(mod_nl)

#goodfit(res, rsd_nl, 0.9)
```

```         
[1] 0.3405887 
[1] 0.4336913 
[1] 0.848482 
[1] 0.8967001 
[1] 0.6353105
```

be splainu

```         
[1] 0.3410027 
[1] 0.4357152 
[1] 0.8456548 
[1] 0.8959828 
[1] 0.6337275 
```

TOT_LVG_AREA

```{r fig.height=5, fig.width=10}
#gg_loess_tot_lvg_area <- ggplot(data, aes(x = TOT_LVG_AREA, y = SALE_PRC)) +
#  geom_point() +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "blue")

#gg_loess_water_dist <- ggplot(data, aes(x = WATER_DIST, y = SALE_PRC)) +
#  geom_point() +
#  theme_bw() +
#  geom_smooth(method = "loess", span = 0.75, color = "blue")


#gg_loess_tot_lvg_area + gg_loess_water_dist
```

Splainai

```{r}
#library(splines)
```

```{r}
#plot(filtered_data$TOT_LVG_AREA, filtered_data$SALE_PRC, 
#     col = "grey", 
#     pch = 20, 
#     main = "Kainos priklausomybė nuo ploto (Splainas)",
#     xlab = "Plotas (kv. pėdos)", 
#     ylab = "Kaina ($)")

# TIESINIS MODELIS
#model_simple <- lm(SALE_PRC ~ TOT_LVG_AREA, data = filtered_data)
#abline(model_simple, col = "blue", lwd = 2)

# NETARALUS SPLAINAS
#model_ns <- lm(SALE_PRC ~ ns(TOT_LVG_AREA , df = 4), data = filtered_data)
#TOT_LVG_AREA_range <- range(filtered_data$TOT_LVG_AREA)
#TOT_LVG_AREA_grid <- seq(from = TOT_LVG_AREA_range[1], to = TOT_LVG_AREA_range[2])

#model_ns_predict <- predict(model_ns , newdata = list(TOT_LVG_AREA = TOT_LVG_AREA_grid), se = T)

#lines(TOT_LVG_AREA_grid , model_ns_predict$fit , col = "red", lwd = 2)

#lines(TOT_LVG_AREA_grid, model_ns_predict$fit + 2*model_ns_predict$se.fit, lty = "dashed", col = "red")
#lines(TOT_LVG_AREA_grid, model_ns_predict$fit - 2*model_ns_predict$se.fit, lty = "dashed", col = "red")

# REGRESIJOS SPLAINAI
#model_bs <- lm(SALE_PRC ~ bs(TOT_LVG_AREA, df = 4), data = filtered_data)
#pred_bs <- predict(model_bs, newdata = list(TOT_LVG_AREA = TOT_LVG_AREA_grid))

#lines(TOT_LVG_AREA_grid, pred_bs, col = "darkgreen", lwd = 2)

# GLODIEJI SPLAINAI
#fit_smooth <- smooth.spline(filtered_data$TOT_LVG_AREA, filtered_data$SALE_PRC, cv = TRUE)
#lines(fit_smooth, col = "purple", lwd = 2)
```

Kvantilių regresija

```{r}
#library(quantreg)
```

```{r}
#fit10 <- rq(SALE_PRC ~ TOT_LVG_AREA, tau = 0.1, data = filtered_data)
#fit50 <- rq(SALE_PRC ~ TOT_LVG_AREA, tau = 0.5, data = filtered_data)
#fit90 <- rq(SALE_PRC ~ TOT_LVG_AREA, tau = 0.9, data = filtered_data)

#res10 <- predict(fit10, newdata = list(TOT_LVG_AREA = TOT_LVG_AREA_grid))
#res50 <- predict(fit50, newdata = list(TOT_LVG_AREA = TOT_LVG_AREA_grid))
#res90 <- predict(fit90, newdata = list(TOT_LVG_AREA = TOT_LVG_AREA_grid))

#plot(filtered_data$TOT_LVG_AREA, filtered_data$SALE_PRC, 
#     col = "lightgrey", pch = 20, 
#     main = "Kvantilių regresija: Plotas vs Kaina",
#     xlab = "Plotas", ylab = "Kaina")

#lines(TOT_LVG_AREA_grid, res10, col = "blue", lwd = 2, lty = 2)
#lines(TOT_LVG_AREA_grid, res50, col = "black", lwd = 3)
#lines(TOT_LVG_AREA_grid, res90, col = "red", lwd = 2, lty = 2)

#legend("topleft", legend = c("90-asis kvantilis", "Mediana", "10-asis kvantilis"),
#       col = c("red", "black", "blue"), lty = c(2, 1, 2), lwd = 2)
```

WATER

```{r}
#model_double_ns <- lm(SALE_PRC ~ ns(WATER_DIST, df = 4) + ns(TOT_LVG_AREA, df = 4), data = filtered_data)

#water_range <- range(filtered_data$WATER_DIST, na.rm = TRUE)
#water_grid <- seq(from = water_range[1], to = water_range[2], length.out = 1000)

#preds_water <- predict(model_water_ns, newdata = list(WATER_DIST = water_grid), se = TRUE)

#plot(filtered_data$WATER_DIST, filtered_data$SALE_PRC, 
#     col = "grey", pch = 20, alpha = 0.3,
#     main = "Kainos priklausomybė nuo atstumo iki vandens (Natūralusis splainas)",
#     xlab = "Atstumas iki vandens (metrai)", 
#     ylab = "Kaina ($)")

#lines(water_grid, preds_water$fit, col = "red", lwd = 3)

#lines(water_grid, preds_water$fit + 2*preds_water$se.fit, lty = "dashed", col = "red")
#lines(water_grid, preds_water$fit - 2*preds_water$se.fit, lty = "dashed", col = "red")

#abline(lm(SALE_PRC ~ WATER_DIST, data = filtered_data), col = "blue", lwd = 2, lty = 3)

#legend("topright", legend = c("Natūralusis splainas", "95% pasikl. interv.", "Tiesinė regresija"),
#       col = c("red", "red", "blue"), lty = c(1, 2, 3), lwd = 2)
```

TOT_LVG_AREA and WATER

```{r}
#library(mgcv)
#gam_model <- gam(SALE_PRC ~ s(WATER_DIST, k = 4) + s(TOT_LVG_AREA, k = 4), data = filtered_data)

#par(mfrow = c(1, 2))
#plot(gam_model, se = TRUE, col = "red", lwd = 2)
```

```{r}
#ggplot(test_data, aes(x = log(SALE_PRC), y =pred)) +
#  geom_point(alpha = 0.3, color = "darkblue") +
#  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
#  labs(title = "Kvantilinė regresija (tau = 0.9): Tikros vs Prognozuotos kainos",
#       x = "Tikra kaina (SALE_PRC)",
#       y = "Prognozuota kaina (0.9 kvantilis)") +
#  theme_minimal()
```
