# Bibliotekos

Užkraunamos reikalingos bibliotekos.

```{r Bibliotekos, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
library(patchwork)
library(corrplot)
library(ppcor)
```

# Duoemnų paruošimas

Įkeliami ir sutvarkomi duomenys.

```{r Import data, message=FALSE, warning=FALSE}
churn_data <- read_csv("../datasets/Customer Churn.csv")

churn_data <- churn_data %>% rename(
  "call_failure" = `Call  Failure`,
  "complains" = Complains,
  "subscription_length" = `Subscription  Length`,
  "charge_amount" = `Charge  Amount`,
  "sec_of_use" = `Seconds of Use`,
  "freq_of_use" = `Frequency of use`,
  "freq_of_SMS" = `Frequency of SMS`,
  "distinct_called_numbers" = `Distinct Called Numbers`,
  "age_group" = `Age Group`,
  "tariff_plan" = `Tariff Plan`,
  "status" = Status,
  "age" = Age,
  "customer_value" = `Customer Value`,
  "churn" = Churn
)

factors <- c("complains", "charge_amount", "age_group", "tariff_plan", "status", "churn")
churn_data[factors] <- lapply(churn_data[factors], as.factor)
```

# Praleistos reikšmės

```{r}
sum(is.na(churn_data))
```

# Išskirtys

```{r}
count_outliers <- function(data, var_name) {
  data %>%
    summarise(
      variable = var_name,
      Q1 = quantile(.data[[var_name]], 0.25),
      Q3 = quantile(.data[[var_name]], 0.75),
      H = Q3 - Q1,
      inner_low = Q1 - 1.5*H,
      inner_high = Q3 + 1.5*H,
      outer_low = Q1 - 3*H,
      outer_high = Q3 + 3*H,
      mild_outliers = sum((.data[[var_name]] < inner_low & .data[[var_name]] > outer_low) | (.data[[var_name]] > inner_high &   .data[[var_name]] < outer_high)),
      extreme_outliers = sum(.data[[var_name]] < outer_low | .data[[var_name]] > outer_high)
      )
}
```

```{r}
numeric_cols <- churn_data %>% 
  dplyr::select(where(is.numeric)) %>% 
  names()

results_list <- lapply(numeric_cols, function(col) count_outliers(churn_data, col))
outlier_summary <- bind_rows(results_list)
outlier_summary
```

```{r}
churn_data %>%
  dplyr::select(where(is.numeric)) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~name, scales = "free") +
  theme_bw() +
  theme(legend.position = "none")
```


# Skaitinės charakteristikos

```{r}
char <- churn_data %>% 
  group_by(churn) %>% 
  summarise(across(where(is.numeric),
            list(min = ~min(.x, na.rm = TRUE), 
                 max = ~max(.x, na.rm = TRUE),
                 mean = ~mean(.x, na.rm = TRUE), 
                 sd = ~sd(.x, na.rm = TRUE),
                 q25 = ~quantile(.x, 0.25, na.rm = TRUE),
                 median = ~median(.x, na.rm = TRUE),
                 q75 = ~quantile(.x, 0.75, na.rm = TRUE)))) %>% 
  pivot_longer(cols = -churn, 
               names_to = c("Variable", ".value"),
               names_pattern = "(.*)_(min|max|mean|sd|median|q25|q75)") %>% 
  mutate(across(where(is.numeric), ~ round(.x, 4)))
char
```

# Atsakas

```{r}
table(churn_data$churn)
```

# Kiekybinių kintamųjų analizė

```{r}
hist1 <- churn_data %>% 
  ggplot(aes(x = customer_value, fill = churn, color = churn)) +
  geom_histogram(position = 'identity', bins = 60, alpha = 0.75) +
  geom_vline(aes(xintercept = 535.5115), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 660, y = 180, label = "535,51"), size = 4, color = "blue") +
  geom_vline(aes(xintercept = 124.8114), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 245, y = 180, label = "124.81"), size = 4, color = "red") +
  labs(x = "Kliento svarba", y = "Dažnis", color = "Pasirinkimas") +
  scale_fill_manual(name = "Pasirinkimas",
                    labels = c("1" = "Atsisakė", "0" = "Neatsisakė"),
                    values = c("0" = "#00BFC4", "1" = "#F8766D")) +
  scale_color_manual(values = c("0" = "#00BFC4", "1" = "#F8766D"),
                     guide = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist1


hist2 <- churn_data %>% 
  ggplot(aes(x = subscription_length, fill = churn, color = churn)) +
  geom_histogram(position = 'identity', bins = 45, alpha = 0.75) +
  geom_vline(aes(xintercept = 32.6625), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 35, y = 180, label = "32,66"), size = 4, color = "blue") +
  geom_vline(aes(xintercept = 31.8949), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 29, y = 180, label = "31,90"), size = 4, color = "red") +
  labs(x = "Abonimento trukmė (mėn.)", y = NULL, color = "Pasirinkimas") +
  scale_fill_manual(name = "Pasirinkimas",
                    labels = c("1" = "Atsisakė", "0" = "Neatsisakė"),
                    values = c("0" = "#00BFC4", "1" = "#F8766D")) +
  scale_color_manual(values = c("0" = "#00BFC4", "1" = "#F8766D"),
                     guide = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist2


hist3 <- churn_data %>% 
  ggplot(aes(x = sec_of_use, fill = churn, color = churn)) +
  geom_histogram(position = 'identity', bins = 60, alpha = 0.75) +
  geom_vline(aes(xintercept = 5014.2241), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 6100, y = 100, label = "5014,22"), size = 4, color = "blue") +
  geom_vline(aes(xintercept = 1566.6323), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 2650, y = 100, label = "1566,63"), size = 4, color = "red") +
  labs(x = "Naudojimo trukmė (s)", y = "Dažnis", color = "Pasirinkimas") +
  scale_fill_manual(name = "Pasirinkimas",
                    labels = c("1" = "Atsisakė", "0" = "Neatsisakė"),
                    values = c("0" = "#00BFC4", "1" = "#F8766D")) +
  scale_color_manual(values = c("0" = "#00BFC4", "1" = "#F8766D"),
                     guide = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist3


hist4 <- churn_data %>% 
  ggplot(aes(x = freq_of_use, fill = churn, color = churn)) +
  geom_histogram(position = 'identity', bins = 60, alpha = 0.75) +
  geom_vline(aes(xintercept = 76.9793), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 90, y = 100, label = "76,98"), size = 4, color = "blue") +
  geom_vline(aes(xintercept = 29.1333), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 45, y = 100, label = "29.13"), size = 4, color = "red") +
  labs(x = "Naudojamo dažnumas (bendras skambučių skaičius)", y = NULL, color = "Pasirinkimas") +
  scale_fill_manual(name = "Pasirinkimas",
                    labels = c("1" = "Atsisakė", "0" = "Neatsisakė"),
                    values = c("0" = "#00BFC4", "1" = "#F8766D")) +
  scale_color_manual(values = c("0" = "#00BFC4", "1" = "#F8766D"),
                     guide = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist4
```


```{r}
combined_hist <- (hist1 + hist2 + hist3 + hist4) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

combined_hist + plot_annotation(
  title = "Klientų rodiklių pasiskirstymas pagal atsisakymą",
  subtitle = "Mažiausias grupių vidurkių skirtumas matomas tarp abonimento trukmės. \n(Brūkšninės vertikalios linijos žymi grupių vidurkius).",
  theme = theme(plot.title = element_text(size = 14),
                plot.subtitle = element_text(size = 12),
                legend.title = element_text(size = 11,),
                legend.text = element_text(size = 10)))
```



# Kokybinių kintamųjų analizė

```{r}
kategoriniai_kintamieji <- names(churn_data)[sapply(churn_data, function(x) !is.numeric(x))]
kategoriniai_kintamieji <- setdiff(kategoriniai_kintamieji, "churn")

for (kintamasis in kategoriniai_kintamieji) {
  cat("\n--- Kryžminė lentelė kintamajam:", kintamasis, "---\n")
  lentele <- table(churn_data[[kintamasis]], churn_data$churn, useNA = "ifany")
  names(dimnames(lentele)) <- c(kintamasis, "Churn")
  print(lentele)
}
```


# Koreliacijos

```{r}
numeric_values <- churn_data %>% 
  dplyr::select(where(is.numeric)) %>% 
  rename(
    "Skambučių sutrikimai" = call_failure,
    "Abonemento trukmė" = subscription_length,
    "Naudojimo trukmė" = sec_of_use,
    "Naudojimo dažnumas" = freq_of_use,
    "SMS dažnumas" = freq_of_SMS,
    "Skirtingi numeriai" = distinct_called_numbers,
    "Amžius" = age,
    "Kliento vertė" = customer_value
  )

options(OutDec = ",")
cor <- cor(numeric_values, method = "spearman")
corrplot(cor, method = "circle", tl.col = "black", type = 'lower', insig='blank',
         addCoef.col ='black',number.cex = 0.8,  diag=FALSE)

mtext("Skaitinių kintamųjų koreliacijų matrica", side = 3, adj = 0, line = 2, cex = 1.17)
#mtext("Didžiausia koreliacija tarp", side = 3, adj = 0, line = 0.95, cex = 0.75)
```

```{r}
daline_cor <- pcor(numeric_values, method = "spearman")
print(daline_cor$estimate)
```

