```{r Bibliotekos, message=FALSE, warning=FALSE}
library(tidyverse)
library(survival)
library(survminer)
library(car)
library(TSHRC)
library(patchwork)
```

# Duomenys

```{r}
data <- read.csv("../datasets/gbsg.csv")
data <- data %>% select(-X)

data$meno <- as.factor(data$meno)
data$hormon <- as.factor(data$hormon)
data$status <- as.factor(data$status)

str(data)
```

```{r}
data <- data %>% mutate(age_group = ifelse(age <=40, '<=40', ifelse(age <=60, '40-60', '>60')))

table(data$age_group)

table(data$age_group, data$status)
```


# Pradinė analizė

```{r}
summary(data)
```

Cenzuravimas is desines, atstitiktinis, nes i tyrima paceintai itraukti skirtingais laikais, kiekvienas stebetas skirtinga trukme

Cenzūruotų stebėjimų dalis

```{r}
attach(data)
prop.table(table(status == 1))
```

```{r}
table(meno)

table(hormon)

table(meno, status)

table(hormon, status)
```

```{r}
char <- data %>% 
  summarise(across(where(is.numeric),
            list(min = ~min(.x, na.rm = TRUE), 
                 max = ~max(.x, na.rm = TRUE),
                 mean = ~mean(.x, na.rm = TRUE), 
                 sd = ~sd(.x, na.rm = TRUE),
                 q25 = ~quantile(.x, 0.25, na.rm = TRUE),
                 median = ~median(.x, na.rm = TRUE),
                 q75 = ~quantile(.x, 0.75, na.rm = TRUE)))) %>% 
  pivot_longer(cols = everything(), 
               names_to = c("Variable", ".value"),
               names_pattern = "(.*)_(min|max|mean|sd|median|q25|q75)") %>% 
  mutate(across(where(is.numeric), ~ round(.x, 4)))
char
```

```{r fig.height=3, fig.width=6.7, message=FALSE, warning=FALSE}
data_long <- data %>%
  dplyr::select(-status, -hormon, -meno, -pid, -grade, -age_group) %>%
  pivot_longer(
    cols = everything(), 
    names_to = "variable", 
    values_to = "value"
  )

data_long$variable <- as.factor(data_long$variable)

data_long %>% 
  ggplot(aes(x = variable, y = value, fill = variable)) +
  geom_boxplot(outlier.alpha = 0.2) +
  facet_wrap(~variable, scales = "free", ncol = 3) + 
  theme_bw() +
  theme(legend.position = 'none') +
  labs(x = 'Kintamaasis', y = 'Reikšmė')

#ggsave(filename = "boxplot.png", width = 6.7, height = 3, units = "in", dpi = 300)
```

```{r fig.height=4, fig.width=6.7, message=FALSE, warning=FALSE}
data_long <- data %>%
  dplyr::select(status, age, size, nodes, pgr, er, rfstime) %>%
  pivot_longer(
    cols = -status,
    names_to = "variable", 
    values_to = "value"
  )

data_long$variable <- as.factor(data_long$variable)
data_long$status <- as.factor(data_long$status)

data_long %>% 
  ggplot(aes(x = status, y = value, fill = status)) +
  geom_boxplot(outlier.alpha = 0.2) +
  facet_wrap(~variable, scales = "free", ncol = 3) + 
  scale_fill_manual(values = c("0" = "#66c2a5", "1" = "#fc8d62"), 
                    labels = c("Cenzūruota", "Įvykis")) +
  labs(title = "Kintamųjų pasiskirstymas pagal statusą",
       x = "Statusas",
       y = "Reikšmė") +
  theme_bw() +
  theme(legend.position = 'bottom')

#ggsave(filename = "boxplot_by_status.png", width = 6.7, height = 4, units = "in", dpi = 300)
```

```{r fig.height=3, fig.width=6.7, warning=FALSE}
status_num <- as.numeric(as.character(data$status))

km_overall <- survfit(Surv(rfstime, status_num) ~ 1, data = data)
ggsurvplot(km_overall,
           data       = data,
           conf.int   = TRUE,
           xlab       = "Laikas (dienos)",
           ylab       = "Išgyvenamumo tikimybė",
           title      = "Kaplan-Meier kreivė (visi pacientai)",
           ggtheme    = theme_minimal())

#ggsave(filename = "KM_all.png", width = 6.7, height = 3, units = "in", dpi = 300)
```

```{r fig.height=3, fig.width=6.7, warning=FALSE}
# KM pagal menopauzę
km_meno <- survfit(Surv(rfstime, status_num) ~ meno, data = data)
ggsurvplot(km_meno,
           data       = data,
           conf.int   = TRUE,
           pval       = FALSE,   # log-rank testas
           legend.labs = c("Prieš menopauzę", "Po menopauzės"),
           xlab       = "Laikas (dienos)",
           title      = "KM kreivė pagal menopauzę",
           ggtheme    = theme_minimal())

#ggsave(filename = "KM_meno.png", width = 6.7, height = 3, units = "in", dpi = 300)
```

```{r}
time_vec   <- data$rfstime
status_vec <- as.numeric(as.character(data$status))
group_vec  <- as.numeric(as.factor(data$meno)) - 1

res <- twostage(time_vec, status_vec, group_vec, nboot = 100)

res
```





```{r fig.height=3, fig.width=6.7, warning=FALSE}
# KM pagal hormoninę terapiją
km_hormon <- survfit(Surv(rfstime, status_num) ~ hormon, data = data)
ggsurvplot(km_hormon,
           data        = data,
           conf.int    = TRUE,
           pval        = TRUE,
           legend.labs = c("Be terapijos", "Su terapija"),
           xlab        = "Laikas (dienos)",
           title       = "KM kreivė pagal hormoninę terapiją",
           ggtheme     = theme_minimal())

#ggsave(filename = "KM_hormon.png", width = 6.7, height = 3, units = "in", dpi = 300)
```

```{r fig.height=3, fig.width=6.7, warning=FALSE}
# KM pagal naviko laipsnį
km_grade <- survfit(Surv(rfstime, status_num) ~ grade, data = data)
ggsurvplot(km_grade,
           data        = data,
           conf.int    = TRUE,
           pval        = TRUE,
           xlab        = "Laikas (dienos)",
           title       = "KM kreivė pagal naviko laipsnį",
           ggtheme     = theme_minimal())

#ggsave(filename = "KM_grade.png", width = 6.7, height = 3, units = "in", dpi = 300)
```

```{r fig.height=4.5, fig.width=6.7, warning=FALSE}
data$status_num <- status_num
data$statusLabel <- ifelse(status_num == 1, "Įvykis", "Cenzūruota")

kiekybiniai_vars <- c("age", "size", "nodes", "pgr", "er")

plots <- lapply(kiekybiniai_vars, function(var) {
  ggplot(data, aes_string(x = var, y = "rfstime", 
                          color = "statusLabel", 
                          shape = "statusLabel")) +
    geom_point(alpha = 0.5, size = 1) +
    scale_color_manual(values = c("Įvykis" = "firebrick", 
                                  "Cenzūruota" = "steelblue")) +
    labs(title = paste("RFS laikas ~", var),
         x = NULL, y = "Dienos",
         color = "Statusas", shape = "Statusas") +
    theme_bw()
})

combined_plot <- wrap_plots(plots, ncol = 2) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = 'bottom')

print(combined_plot)

#ggsave(filename = "scater.png", width = 6.7, height = 4.5, units = "in", dpi = 300)
```

```{r}
data$meno   <- as.factor(data$meno)
data$grade  <- as.factor(data$grade)
data$hormon <- as.factor(data$hormon)
```

# Kokso modelis

```{r}
status_num <- as.numeric(as.character(data$status))

cox_full <- coxph(Surv(rfstime, status_num) ~ 
                    age_group + meno + size + grade + 
                    nodes + pgr + er + hormon, data = data)
summary(cox_full)
```

## Multikolinearumas

```{r}
vif(cox_full)
```


## Išskirtys

```{r}
2 / sqrt(686)
```

```{r}
dfbeta <- residuals(cox_full, type="dfbeta")
par(mfrow=c(2, 2))
for (j in 1:9) {
  plot(dfbeta[, j],
  ylab=names(coef(cox_full))[j])
  abline(h=0, lty=2)
}
```

```{r}
threshold <- 2 / sqrt(686)
dfbeta <- residuals(cox_full, type="dfbeta")
par(mfrow=c(3, 3))

for (j in 1:9) {
  y_reikšmės <- dfbeta[, j]
  y_limitas <- max(c(abs(y_reikšmės), threshold)) * 1.1
  
  plot(dfbeta[, j],
       ylab=names(coef(cox_full))[j],
       main=paste(names(coef(cox_full))[j]),
       col="steelblue", 
       #ylim = c(-y_limitas, y_limitas,
       pch=20)
  
  abline(h=0, lty=1, col="black") 
  abline(h = threshold, lty = 2, col = "red")
  abline(h = -threshold, lty = 2, col = "red")
}
```


## PH prielaida

```{r}
ph_test <- cox.zph(cox_full)
print(ph_test)
plot(ph_test)
```


```{r}
unfold_data <- function(data, time = "tenure", event = "Churn") {
  out <- data[rep(seq_len(nrow(data)), pmax(data[[time]], 1)), ]
  
  out$start <- unlist(lapply(data[[time]], function(t) {
    if (t <= 0) 0 else seq(0, t - 1)
  }))
  
  out$stop <- unlist(lapply(data[[time]], function(t) {
    if (t <= 0) 1 else seq(1, t)
  }))
  
  out[[event]] <- 0
  
  last_rows <- cumsum(pmax(data[[time]], 1))
  out[[event]][last_rows] <- data[[event]]
  
  rownames(out) <- NULL
  out
}
```


```{r}
data_long_daily <- unfold_data(
  data = data, 
  time = "rfstime",
  event = "status_num"
)
```


```{r}
model_daily <- coxph(
  Surv(start, stop, status_num) ~ 
    age + meno + size + grade + nodes + pgr + er + hormon + meno:stop, 
  data = data_long_daily)
```
```{r}
summary(model_daily)
```

```{r}
ph_test <- cox.zph(model_daily)
print(ph_test)
plot(ph_test)
```


## Tiesiškumo prielaida


```{r}
coef(cox_full)
```

```{r message=FALSE, warning=FALSE}
data <- data %>%
  mutate(log_nodes = log(nodes + 1))

cox_full2 <- coxph(Surv(rfstime, status_num) ~ 
                    age + meno + size + grade + 
                    log_nodes + pgr + er + hormon, data = data)

res <- residuals(cox_full2, type = "martingale")
target_vars <- c("age", "size", "log_nodes", "pgr", "er")
b <- coef(cox_full2)[target_vars]

plot_data <- data %>%
  select(all_of(target_vars)) %>%
  mutate(residuals = res) %>%
  pivot_longer(cols = all_of(target_vars), names_to = "variable", values_to = "x_value") %>%
  mutate(
    beta = b[variable],
    comp_residual = beta * x_value + residuals,
    variable = factor(variable, levels = target_vars)
  )

p1 <- ggplot(plot_data, aes(x = x_value, y = residuals)) +
  geom_point(alpha = 0.5, color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  geom_smooth(method = "loess", method.args = list(degree = 1), se = TRUE, color = "blue", span = 0.75) +
  facet_wrap(~variable, scales = "free_x", nrow = 1) +
  labs(x = NULL, y = "Martingale Residuals") +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold", size = 11))

p2 <- ggplot(plot_data, aes(x = x_value, y = comp_residual)) +
  geom_point(alpha = 0.5, color = "black") +
  geom_smooth(method = "lm", linetype = "dashed", se = FALSE, color = "darkgray") +
  geom_smooth(method = "loess", method.args = list(degree = 1), se = TRUE, color = "blue", span = 0.75) +
  facet_wrap(~variable, scales = "free_x", nrow = 1) +
  labs(x = "Covariate Value", y = "Component + Residual") +
  theme_minimal() +
  theme(strip.text = element_blank())

final_plot <- p1 / p2

print(final_plot)
```







